language: ruby
rvm:
  - "2.2.0"
env:
  - DB=mysql
script: 
  - bundle exec rake db:migrate
  - bundle exec rspec spec/
before_script:
  - mysql -e 'create database AutismApp'
bundler_args: --binstubs=./bundler_stubs